// Initial product data
const products = [
    {
      id: 1001,
      name: "dress",
      category: "Women Clothes",
      price: 300,
      originCountry: "Italy",
    },
    {
      id: 1002,
      name: "coat",
      category: "Women Clothes",
      price: 800,
      originCountry: "France",
    },
    {
      id: 1003,
      name: "jeans",
      category: "Men Clothes",
      price: 700,
      originCountry: "Italy",
    },
    {
      id: 1004,
      name: "jacket",
      category: "Men Clothes",
      price: 500,
      originCountry: "Italy",
    },
    {
      id: 1005,
      name: "romper",
      category: "Baby Clothes",
      price: 100,
      originCountry: "France",
    },
    {
      id: 1006,
      name: "sweater",
      category: "Women Clothes",
      price: 400,
      originCountry: "USA",
    },
    {
      id: 1007,
      name: "shirt",
      category: "Men Clothes",
      price: 250,
      originCountry: "England",
    },
    {
      id: 1008,
      name: "onesie",
      category: "Baby Clothes",
      price: 80,
      originCountry: "Germany",
    },
    {
      id: 1009,
      name: "skirt",
      category: "Women Clothes",
      price: 220,
      originCountry: "France",
    },
    {
      id: 1010,
      name: "tie",
      category: "Men Clothes",
      price: 75,
      originCountry: "Italy",
    },
    {
      id: 1011,
      name: "bodysuit",
      category: "Baby Clothes",
      price: 120,
      originCountry: "Spain",
    },
    {
      id: 1012,
      name: "blouse",
      category: "Women Clothes",
      price: 180,
      originCountry: "Spain",
    },
    {
      id: 1013,
      name: "suit",
      category: "Men Clothes",
      price: 900,
      originCountry: "Italy",
    },
    {
      id: 1014,
      name: "socks",
      category: "Baby Clothes",
      price: 15,
      originCountry: "USA",
    },
    {
      id: 1015,
      name: "jumpsuit",
      category: "Women Clothes",
      price: 350,
      originCountry: "France",
    },
    {
      id: 1016,
      name: "vest",
      category: "Men Clothes",
      price: 120,
      originCountry: "England",
    },
    {
      id: 1017,
      name: "hat",
      category: "Baby Clothes",
      price: 30,
      originCountry: "Germany",
    },
    {
      id: 1018,
      name: "dress",
      category: "Baby Clothes",
      price: 350,
      originCountry: "Germany",
    },
    {
      id: 1019,
      name: "leggins",
      category: "Women Clothes",
      price: 380,
      originCountry: "Moldova",
    },
    {
      id: 1020,
      name: "pants",
      category: "Men Clothes",
      price: 260,
      originCountry: "Germany",
    },
  ];

  export const getProducts = () => {
    return products;
  }